<a href="https://colab.research.google.com/github/Abinaykumar-Patnala/MachineLearning/blob/main/ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install pandas

In [ ]:
import numpy as np
n = np.arange(10)
print(n)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
N=n.reshape(2,5)
print(N)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [ ]:
M=n.reshape(5,2)
print(M)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
print(np.dot(M,N))

[[  5   6   7   8   9]
 [ 15  20  25  30  35]
 [ 25  34  43  52  61]
 [ 35  48  61  74  87]
 [ 45  62  79  96 113]]


In [ ]:
n2=n[n%2!=0]
print(n2)

[1 3 5 7 9]


In [ ]:
m=[n>2]
print(m)

[array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])]


In [ ]:
n3=np.arange(20)
n3[n3%2!=0]=15
print(n3)

[ 0 15  2 15  4 15  6 15  8 15 10 15 12 15 14 15 16 15 18 15]


In [ ]:
P=np.array([25,14,12,28,3])
P[P%2==0]*=-1
print(P)

[ 25 -14 -12 -28   3]


In [ ]:
#
from google.colab import files
uploaded = files.upload()
import pandas as pd
import pandas as pd
data = pd.read_csv('/content/favorite_music_dataset.csv')
print(data.head())


In [ ]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
# Load dataset
iris = datasets.load_iris()
X = iris.data
y = iris.target
# Split dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
# Create and train the model
clf = RandomForestClassifier(n_estimators=100)
clf.fit(X_train, y_train)
# Make predictions
y_pred = clf.predict(X_test)
# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

Accuracy: 1.00
