<a href="https://colab.research.google.com/github/Abinaykumar-Patnala/MachineLearning/blob/main/ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install pandas

In [ ]:
import numpy as np
n = np.arange(10)
print(n)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
N=n.reshape(2,5)
print(N)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [ ]:
M=n.reshape(5,2)
print(M)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
print(np.dot(M,N))

[[  5   6   7   8   9]
 [ 15  20  25  30  35]
 [ 25  34  43  52  61]
 [ 35  48  61  74  87]
 [ 45  62  79  96 113]]


In [ ]:
n2=n[n%2!=0]
print(n2)

[1 3 5 7 9]


In [ ]:
m=[n>2]
print(m)

[array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])]


In [ ]:
n3=np.arange(20)
n3[n3%2!=0]=15
print(n3)

[ 0 15  2 15  4 15  6 15  8 15 10 15 12 15 14 15 16 15 18 15]


In [ ]:
P=np.array([25,14,12,28,3])
P[P%2==0]*=-1
print(P)

[ 25 -14 -12 -28   3]


In [ ]:
#
from google.colab import files
uploaded = files.upload()
import pandas as pd
import pandas as pd
data = pd.read_csv('/content/favorite_music_dataset.csv')
print(data.head())


In [ ]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
# Load dataset
iris = datasets.load_iris()
X = iris.data
y = iris.target
# Split dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
# Create and train the model
clf = RandomForestClassifier(n_estimators=100)
clf.fit(X_train, y_train)
# Make predictions
y_pred = clf.predict(X_test)
# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

Accuracy: 1.00


01-08-2025

In [50]:
#constant features
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import VarianceThreshold
df=pd.read_csv('/content/airlines_flights_data.csv')
df.shape
df['new_column']=0
# [col for col in df.columns if df[col].isnull().sum() > 0]
# x_train, x_test, y_train, y_test = train_test_split(
#     df.drop(labels=['days_left'], axis=1),
#     df['days_left'],
#     test_size=0.3,
#     random_state=0
# )
# Select only numeric columns from x_train
x_train_numeric = df.select_dtypes(include=[np.number]).columns

# Find constant features
constant_features = [feature for feature in x_train_numeric if df[feature].std() == 0]
print("Number of constant features:", len(constant_features))
print("Constant features:", constant_features)
df.drop(labels=constant_features,axis=1,inplace=True)
print(df.head())

Number of constant features: 1
Constant features: ['new_column']
   index   airline   flight source_city departure_time stops   arrival_time  \
0      0  SpiceJet  SG-8709       Delhi        Evening  zero          Night   
1      1  SpiceJet  SG-8157       Delhi  Early_Morning  zero        Morning   
2      2   AirAsia   I5-764       Delhi  Early_Morning  zero  Early_Morning   
3      3   Vistara   UK-995       Delhi        Morning  zero      Afternoon   
4      4   Vistara   UK-963       Delhi        Morning  zero        Morning   

  destination_city    class  duration  days_left  price  
0           Mumbai  Economy      2.17          1   5953  
1           Mumbai  Economy      2.33          1   5953  
2           Mumbai  Economy      2.17          1   5956  
3           Mumbai  Economy      2.25          1   5955  
4           Mumbai  Economy      2.33          1   5955  


In [32]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

# Load dataset
df = pd.read_csv('/content/airlines_flights_data.csv')

# Check shape
print("Shape:", df.shape)

# Check for null columns
null_columns = [col for col in df.columns if df[col].isnull().sum() > 0]
print("Columns with nulls:", null_columns)

# Train-test split
# Step 1: Select only numeric columns from x_train
x_train_numeric = x_train.select_dtypes(include=[np.number])

# Step 2: Find constant features (std = 0)
constant_features = [feature for feature in x_train_numeric.columns if x_train_numeric[feature].std() == 0]

# Step 3: Print results
print("Number of constant features:", len(constant_features))
print("Constant features:", constant_features)


Shape: (300153, 12)
Columns with nulls: []
Number of constant features: 0
Constant features: []


In [ ]:
#Quasi Constant
