<a href="https://colab.research.google.com/github/Abinaykumar-Patnala/MachineLearning/blob/main/ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install pandas

In [ ]:
import numpy as np
n = np.arange(10)
print(n)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
N=n.reshape(2,5)
print(N)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [ ]:
M=n.reshape(5,2)
print(M)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
print(np.dot(M,N))

[[  5   6   7   8   9]
 [ 15  20  25  30  35]
 [ 25  34  43  52  61]
 [ 35  48  61  74  87]
 [ 45  62  79  96 113]]


In [ ]:
n2=n[n%2!=0]
print(n2)

[1 3 5 7 9]


In [ ]:
m=[n>2]
print(m)

[array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])]


In [ ]:
n3=np.arange(20)
n3[n3%2!=0]=15
print(n3)

[ 0 15  2 15  4 15  6 15  8 15 10 15 12 15 14 15 16 15 18 15]


In [ ]:
P=np.array([25,14,12,28,3])
P[P%2==0]*=-1
print(P)

[ 25 -14 -12 -28   3]


In [ ]:
#
from google.colab import files
uploaded = files.upload()
import pandas as pd
import pandas as pd
data = pd.read_csv('/content/favorite_music_dataset.csv')
print(data.head())


In [ ]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
# Load dataset
iris = datasets.load_iris()
X = iris.data
y = iris.target
# Split dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
# Create and train the model
clf = RandomForestClassifier(n_estimators=100)
clf.fit(X_train, y_train)
# Make predictions
y_pred = clf.predict(X_test)
# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

Accuracy: 1.00


01-08-2025

In [ ]:
#constant features
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import VarianceThreshold
df=pd.read_csv('/content/airlines_flights_data.csv')
df.shape
df['new_column']=0
# [col for col in df.columns if df[col].isnull().sum() > 0]
# x_train, x_test, y_train, y_test = train_test_split(
#     df.drop(labels=['days_left'], axis=1),
#     df['days_left'],
#     test_size=0.3,
#     random_state=0
# )
# Select only numeric columns from x_train
x_train_numeric = df.select_dtypes(include=[np.number]).columns

# Find constant features
constant_features = [feature for feature in x_train_numeric if df[feature].std() == 0]
print("Number of constant features:", len(constant_features))
print("Constant features:", constant_features)
df.drop(labels=constant_features,axis=1,inplace=True)
print(df.head())

Number of constant features: 1
Constant features: ['new_column']
   index   airline   flight source_city departure_time stops   arrival_time  \
0      0  SpiceJet  SG-8709       Delhi        Evening  zero          Night   
1      1  SpiceJet  SG-8157       Delhi  Early_Morning  zero        Morning   
2      2   AirAsia   I5-764       Delhi  Early_Morning  zero  Early_Morning   
3      3   Vistara   UK-995       Delhi        Morning  zero      Afternoon   
4      4   Vistara   UK-963       Delhi        Morning  zero        Morning   

  destination_city    class  duration  days_left  price  
0           Mumbai  Economy      2.17          1   5953  
1           Mumbai  Economy      2.33          1   5953  
2           Mumbai  Economy      2.17          1   5956  
3           Mumbai  Economy      2.25          1   5955  
4           Mumbai  Economy      2.33          1   5955  


In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
df = pd.read_csv('/content/airlines_flights_data.csv')
print("Shape:", df.shape)
null_columns = [col for col in df.columns if df[col].isnull().sum() > 0]
print("Columns with nulls:", null_columns)
x_train_numeric = x_train.select_dtypes(include=[np.number])
constant_features = [feature for feature in x_train_numeric.columns if x_train_numeric[feature].std() == 0]
print("Number of constant features:", len(constant_features))
print("Constant features:", constant_features)


Shape: (300153, 12)
Columns with nulls: []
Number of constant features: 0
Constant features: []


In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import chi2
from sklearn.feature_selection import f_classif
df=pd.read_csv('/content/drive/MyDrive/ML/titanic_train.csv')

#constant_features
constant_features = [features for features in df.columns if df[features].std==0]
print("constant features:",constant_features)
#quasiconstant features
quasi_constant_features = [col for col in df.columns if df[col].value_counts(normalize=True).max()>0.99]
print("Quasi-constant features:", quasi_constant_features)
df['Sex']=df['Sex'].map({"male":1,"female":0})
df["Embarked"]=df['Embarked'].map({"S":1,"C":0})
print(df.head())
X_train,X_test,y_train,y_test=train_test_split(df[["Pclass","Sex","Embarked"]],df["Survived"],test_size=0.3,random_state=42)
#chi-square
chi_value=chi2(X_train.fillna(0),y_train)
print("chi_square:",chi_value)
pvalues=pd.Series(chi_value[1])
pvalues.index=X_train.columns
pvalues.sort_values(ascending=True)
#anova
chi_value,pvalue = f_classif(X,y)


constant features: []
Quasi-constant features: []
   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    1  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    0  38.0      1      0   
2                             Heikkinen, Miss. Laina    0  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    0  35.0      1      0   
4                           Allen, Mr. William Henry    1  35.0      0      0   

             Ticket     Fare Cabin  Embarked  
0         A/5 21171   7.2500   NaN       1.0  
1          PC 17599  71.2833   C85       0.0  
2  STON/O2. 3101282   7.9250   NaN       1.0  
3            113803  53.1000  C123       1.0  
4          

Sex         7.664426e-15
Pclass      3.015427e-05
Embarked    2.969504e-02
dtype: float64